cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    hungrypanda:
      name: Hungry Panda
      email: jsmith@gmail.com
      password: y@NK5MhRF&7AmdA91GyQ
      roles:
      - admin
      - editor
      - viewer
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: abc
      roles:
      - admin
      - editor
      - viewer
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      first_name: Rebecca
      last_name: Briggs
      logged_in: false
      password: def
      roles:
      - viewer

